---
- hosts: all
  become: true
  tasks:  
    - name: Install apache
      ansible.builtin.apt:
        name: apache2
    - name: Start apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
    - name: Move index.html
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
